FROM bitwalker/alpine-elixir-phoenix:latest

EXPOSE 80

ARG SECRET_KEY_BASE=${SECRET_KEY_BASE}
ARG CHAT_USER=${CHAT_USER}
ARG CHAT_PASS=${CHAT_PASS}
ARG CHAT_CHANNEL=${CHAT_CHANNEL}
ARG SNAKE_AUTHOR=${SNAKE_AUTHOR}
ARG SNAKE_COLOR=${SNAKE_COLOR}
ARG SNAKE_HEAD=${SNAKE_HEAD}
ARG SNAKE_TAIL=${SNAKE_TAIL}
ARG TURN_TIMEOUT_BUFFER=${TURN_TIMEOUT_BUFFER}
ARG TURN_TIMEOUT_OVERRIDE=${TURN_TIMEOUT_OVERRIDE}

ENV PORT=80 MIX_ENV=prod

ADD mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

ADD . .

RUN mix compile

CMD ["mix", "phx.server"]
