FROM bitwalker/alpine-elixir-phoenix:latest

EXPOSE 5000

ARG SECRET_KEY_BASE=${SECRET_KEY_BASE}
ARG CHAT_USER=${CHAT_USER}
ARG CHAT_PASS=${CHAT_PASS}
ARG CHAT_CHANNEL=${CHAT_CHANNEL}
ARG SNAKE_AUTHOR=${SNAKE_AUTHOR}
ARG SNAKE_COLOR=${SNAKE_COLOR}
ARG SNAKE_HEAD=${SNAKE_HEAD}
ARG SNAKE_TAIL=${SNAKE_TAIL}
ARG TURN_TIMEOUT_BUFFER=${TURN_TIMEOUT_BUFFER}

ENV PORT=5000 MIX_ENV=prod

ADD mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

ADD . .

RUN mix compile

USER default

CMD ["mix", "phx.server"]
